services:
    backend:
        build: .
        image: my-backend-image:latest
        container_name: my-backend-container
        ports:
            - 8000:8000
        command: uvicorn main:app --host 0.0.0.0 --port 8000