name: demo
on: [push]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print to console
        run: echo Hello GH Actions!
      - name: print 2 lines
        run: |
          echo first
          echo second
        
        
